version: '3.8'
services:
  db:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  web:
    build: .
    command: bundle exec rails s -p 3333 -b '0.0.0.0'
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle:cached
    ports:
      - '3333:3333'
    depends_on:
      - db
volumes:
  mysql-data:

volumes:
  mysql_data:
  bundle_data:
