version: "3.8"
services:
  db:
    container_name: db
    image: mysql:5.7.30
    environment:
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
  api:
    container_name: api
    build: .
    image: api
    command: bundle exec rails s -p 3333 -b '0.0.0.0'
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle:cached
    ports:
      - 3333:3333
    depends_on:
      - db

volumes:
  mysql_data:
  bundle_data:
